pipeline {
    agent docker-agent-python
    stages {
        stage('Install Docker Compose') {
            steps {
                script {
                    // Install Docker Compose if it's not available
                    sh '''
                    if ! [ -x "$(command -v docker-compose)" ]; then
                        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                        chmod +x /usr/local/bin/docker-compose
                    fi
                    '''
                }
            }
        }
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build and Run Containers') {
            steps {
                script {
                    dir('Task3') {
                        sh 'docker-compose up -d --build'
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                dir('Task3') {
                    sh 'docker-compose down'
                }
            }
        }
    }
}
