pipeline {
    agent {
        docker {
            image 'docker/compose:1.29.2'  // Use a Docker image with Docker Compose
            args '-v /var/run/docker.sock:/var/run/docker.sock'  // Bind Docker socket
        }
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build and Run Containers') {
            steps {
                script {
                    dir('Task3') {
                        // Build and run Docker Compose services
                        sh 'docker-compose up -d --build'
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                dir('Task3') {
                    // Stop and remove the containers after the pipeline
                    sh 'docker-compose down'
                }
            }
        }
    }
}
